version: '3.1'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:23.4-alpine
    environment:
      - CLICKHOUSE_DB=clickhouse_1
      - CLICKHOUSE_USER=ale
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123" # HTTP API Port for http requests. used by JDBC, ODBC and web interfaces.
      - "9000:9000" # Native Protocol port
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
      - clickhouse-config:/etc/clickhouse-server/config.d
      - clickhouse-user_settings:/etc/clickhouse-server/users.d
      - clickhouse-init:/docker-entrypoint-initdb.d

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

#    healthcheck:
#      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
